version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${ADMIN_DIR}:/opt/www/dashboard/:rw
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${API_SERVER_DIR}/storage/sql:/docker-entrypoint-initdb.d:rw
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${E7_PARTNER_DATABASE}"
      TZ: Asia/Shanghai
    networks:
      - default


  redis:
    image: redis
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default


  app:
    #    image: registry.cn-hangzhou.aliyuncs.com/e7/partner:v1
    build:
      context: config/app
    container_name: app
    ports:
      - "${PHP_HYPERF_PORT}:9501"
    volumes:
      - ${DATA_DIR}/mysql:/www/server/data:rw
      - ${API_SERVER_DIR}:/www/wwwroot/server:rw
    #      - ${DATA_DIR}/redis:/www/server/redis/:rw
    environment:
      LANG: en_US.UTF-8
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - redis
    networks:
      - default


networks:
  default: